//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace SkillEditor
{
	public class AnimationController: Singleton<AnimationController>
	{
		public AnimationClip[] modelAnimationClips;
		private PraseSkillBean praseSkillBean = new PraseSkillBean();

		public override void UnInitialize ()
		{
			base.UnInitialize ();
			if (modelAnimationClips != null) {
				modelAnimationClips = null;		
			}
		}
		public AnimationController ()
		{
		}

		public void DisplaySkill(){

		}

		void InitSkillBean(SkillBean bean){

		}
	}
}

