//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace MonsterAI.AI
{
	public class ActionCmdInstance
	{
		public const int INVALID_INDEX = -1;
		public int m_cmdIndex;

		public float m_movCountTime = 0;
		public float m_actCountTime = 0;
		public float m_localTime = 0;
		public bool m_isMovCmdDone = false;
		public bool m_isActCmdDone = false;

		public bool IsValid() { return m_cmdIndex != INVALID_INDEX; }

		public ActionCmdInstance( int index ) {
			m_cmdIndex = index;
		}
	}
}

